### ISSUE TITLE
资源与用户关联

### ISSUE THREAD

**Issue by SuperSnowYao** [easy-rbac-team/easyRBAC#12]
资源与用户关联，个人认为这是一个图省事和偷懒的设计。因为用户与角色已经有一种关系，而角色与资源也有一种关系，完全可以实现这样的关联设计。而通过资源与用户直接关联，跨过这种设计有关系，一是在设计上是冗余的；二是在设计上也显得有些混乱；用户完全是有一种角色的，只要是存在于系统当中，否则他是一种凭空的存在吗？这是比强牵强的，设计线还是要清晰比较好。

**Comment by uliian** [comment]
在我的实际工作中，反而觉得这个设计是很符合实际需求的一种设计，在很多的特定场景下，这种设计十分有用。你说偷懒也无不可，但是对于易变的、临时的、针对特定用户的场景下，这一设计显得十分有用
